version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: micro-uisp_server_1
      APP_PORT: 80

  server:
    image: nico640/docker-unms:2.4.143
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    ports:
      - 9443:9443
      - 2055:2055/udp
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - HTTPS_PORT=9443
      - PUBLIC_HTTPS_PORT=9443
      - PUBLIC_WS_PORT=9443
