version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: micro-teslamate_server_1
      APP_PORT: 4000

  server:
    image: teslamate/teslamate:1.30.1
    volumes:
      - ${APP_DATA_DIR}/data/import:/opt/app/import
    ports:
      - 4000:4000
    restart: unless-stopped
    environment:
      - ENCRYPTION_KEY=${APP_PASSWORD}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=moneyprintergobrrr
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=micro-teslamate_db_1
      - MQTT_HOST=mosquitto
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=moneyprintergobrrr
      - POSTGRES_DB=teslamate
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    restart: always

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=moneyprintergobrrr
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=micro-teslamate_db_1
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000
    volumes:
      - ${APP_DATA_DIR}/data/grafana:/var/lib/grafana
    depends_on:
      - db

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ${APP_DATA_DIR}/data/mosquitto/conf:/mosquitto/config
      - ${APP_DATA_DIR}/data/mosquitto/data:/mosquitto/data