version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: micro-blesta_server_1
      APP_PORT: 8080

  server:
    build:
      context: .
    restart: unless-stopped
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/config:/var/www/html/config
      - ${APP_DATA_DIR}/data/cache:/var/www/html/cache
      - ${APP_DATA_DIR}/data/uploads:/var/www/uploads
    depends_on:
      - db

  db:
    image: mariadb:11.4.3
    environment:
      - MARIADB_USER=blesta
      - MARIADB_PASSWORD=moneyprintergobrrr
      - MARIADB_DATABASE=blesta
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    restart: always