version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: micro-blesta_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/micro-app-store/blesta:5.10.2
    restart: unless-stopped
    environment:
      - MYSQL_HOST=micro-blesta_db_1
      - MYSQL_USER=blesta
      - MYSQL_PASSWORD=moneyprintergobrrr
      - MYSQL_DATABASE=blesta
    volumes:
      - ${APP_DATA_DIR}/data/config:/var/www/html/config
      - ${APP_DATA_DIR}/data/cache:/var/www/html/cache
      - ${APP_DATA_DIR}/data/uploads:/var/www/uploads
    depends_on:
      - db

  db:
    image: mariadb:11.4.3
    user: "1000:1000"
    environment:
      - MARIADB_USER=blesta
      - MARIADB_PASSWORD=moneyprintergobrrr
      - MARIADB_DATABASE=blesta
      - MARIADB_ROOT_PASSWORD=moneyprintergobrrr
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    restart: always